# Generated by Django 4.2.13 on 2024-10-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_bed_image_alter_post_image_alter_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontact',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_contact', to='rental.room'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('VACUITY', 'Trống'), ('NONVACUITY', 'Đã thuê')], default='VACUITY', max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalcontact',
            name='status',
            field=models.CharField(choices=[('CANCEL', 'Đã Hủy'), ('PROCESSING', 'Đang xử lý'), ('SUCCESS', 'Thành công'), ('FAIL', 'Từ chối')], default='PROCESSING', max_length=255),
        ),
    ]
